apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app-container
          image: 244706281787.dkr.ecr.ap-south-1.amazonaws.com/circleci  
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: nodejs-app




# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nodejs-app-deployment
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: nodejs-app
#   template:
#     metadata:
#       labels:
#         app: nodejs-app
#     spec:
#       containers:
#         - name: nodejs-app-container
#           image: 244706281787.dkr.ecr.ap-south-1.amazonaws.com/circleci:latest
#           ports:
#             - containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nodejs-app-service
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 3000
#   selector:
#     app: nodejs-app




# # node-aws-pipeline\k8s-deployment.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nodejs-app-deployment
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: nodejs-app
#   template:
#     metadata:
#       labels:
#         app: nodejs-app
#     spec:
#       containers:
#         - name: nodejs-app-container
#           image: 244706281787.dkr.ecr.ap-south-1.amazonaws.com/circleci:latest
#           ports:
#             - containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nodejs-app-service
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 3000
#   selector:
#     app: nodejs-app
